Image processing and file size validation
amfoss/cms pull request #16
Opened 2019-02-24 06:46 UTC by C-Anirudh

Used `django-imagekit` to compress the uploaded images, without adversely affecting their quality and converted each uploaded image to JPEG format (best format for lossy compression).

Also created `validators.py` file in `gallery` app which limits the size of any uploaded image or file to 2MB (can be modified as per requirement later), and displays an error message if the size limit is exceeded.
Sample error message :
![file_error](https://user-images.githubusercontent.com/40494926/53296068-0aa8da80-382e-11e9-9daf-b5849a930a3b.png)

2019-02-24 07:06 UTC, aswinshenoy commented
This pull request **fixes 5 alerts** when merging 73a35f2291fce2cd0dcd4377d66b968b50457622 into 33efb44e13f989b81a4427341f457c1f2ca3c0de - [view on LGTM.com](https://lgtm.com/projects/g/amfoss/cms/rev/pr-8cbc4b85ada085b1b6805c569920fe48bd656e0d)

**fixed alerts:**

* 5 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

2019-02-24 08:58 UTC, aswinshenoy requested changes
Can make the changes to allow uploads till 10mb, and put process_image_field_specs together somewhere and import it? 
Also, can you include the before and after size of image upload (or document) as screenshot or something.

2019-02-24 08:58 UTC, aswinshenoy commented on activity/models.py
> +processed_image_field_specs = {
can't we import this too everywhere?

2019-02-24 08:58 UTC, aswinshenoy commented on gallery/validators.py
> +        raise ValidationError("The maximum file size that can be uploaded is 2MB.")
make it 10MB as limit, but it should compress the image well below 500kb.
For documents, keep 10mb as limit, i dont see compression required for documents.

2019-02-24 08:58 UTC, aswinshenoy commented on status/admin.py
> +    fields= (('title','due_date'),('status','tags'),('assignees','team'),'description','updates')
:+1:

2019-02-24 15:28 UTC, aswinshenoy commented
This pull request **fixes 5 alerts** when merging 79018eedabe4270be9ebda6c3780cdeb915457e3 into 7a525d8fbf000601f5fa47a9848f1cd802d43daa - [view on LGTM.com](https://lgtm.com/projects/g/amfoss/cms/rev/pr-e355e04b0ffa65130e7f37ad455776b957b63576)

**fixed alerts:**

* 5 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

2019-02-24 20:00 UTC, aswinshenoy approved these changes

2019-02-24 20:04 UTC, aswinshenoy commented
@C-Anirudh  ```django-imagekit``` needs to be installed for the plugin to be running, I think you forgot to add it to the ```requirements.txt``` file.

2019-02-25 01:48 UTC, C-Anirudh commented
I have added it, it was visible to me as a change when I created the PR.

On Mon, 25 Feb 2019, 01:34 Ashwin Shenoy, <notifications@github.com> wrote:

> @C-Anirudh <https://github.com/C-Anirudh> django-imagekit needs to be
> installed for the plugin to be running, I think you forgot to add it to the
> requirements.txt file.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/amfoss/cms/pull/16#issuecomment-466811604>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AmnnTiHG7adYK38ixBdw87on3Lb-hM5-ks5vQvBigaJpZM4bOX90>
> .
>

2019-02-25 06:00 UTC, aswinshenoy commented
@C-Anirudh can you kindly resolve the conflicts too? Just pull the changes from the master to your branch, it should work :+1:

2019-02-25 12:43 UTC, aswinshenoy commented
This pull request **fixes 5 alerts** when merging 2ad3f57ab3d133fb0f8a46cee255da8b557dd4be into b624f5b09dbd0271d783f020d6b06e41ff410176 - [view on LGTM.com](https://lgtm.com/projects/g/amfoss/cms/rev/pr-6f38caa0f3d764a5067db1d5375b6c1fe298fef2)

**fixed alerts:**

* 5 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

2019-02-25 12:51 UTC, aswinshenoy approved these changes

2019-02-25 12:51 UTC, aswinshenoy commented on blog/models.py
> +    tags = models.ManyToManyField(Tag,verbose_name='Tag', blank=True)
its always adviced to reformat your code (all the files) before committing, this ensures proper spacing and indentation are in place automatically.

2019-02-25 12:51 UTC, merged